title: Default Page

columns:
    main:
        width: 2/3
        sections:
            page:
                type: fields
                fields:
                    h1:
                        type: text
                    lead:
                        type: textarea
                        buttons:
                            - link
                    pageContent:
                        label: Content
                        type: blocks
            images:
                type: files
                multiple: true
                layout: table
                query: page.images
                empty: No images attached yet.
                columns:
                    alt: true
                    caption: true

    sidebar:
        width: 1/3
        fields:
            metattitle:
                label: Meta Title
                type: text
                help: Used for the page title. Not required, will fall back to the H1.
            description:
                type: textarea
                buttons: false
            visual:
                type: files
                multiple: false
                query: page.images
            showupdated:
                label: Show Updated Date
                type: toggle
            related:
                type: pages
                help: Use for related slash pages.
