title: Site

tabs:
    site:
        title: Site
        sections:
            pages:
                type: pages

    config:
        title: Config
        columns:
            main:
                width: 2/3
                fields:
                    description:
                        type: textarea
                        buttons: false

            sidebar:
                width: 1/3
                fields:
                    shorttitle:
                        label: Short Title
                        type: text
                        width: 1/2
                        help: A shorter version of the site title

                    mastodonuser:
                        label: Mastodon Username
                        type: text
                        width: 1/2
                        icon: mastodon
